export const PARKING_DATA = [
  {
    id: 'p1',
    name: 'Сүхбаатарын талбайн зогсоол',
    address: 'Сүхбаатарын талбай, урд талд',
    lat: 47.918,
    lng: 106.917,
    priceMNT: 2000,
    available: true,
    distanceKm: 0.5,
    totalSlots: 50,
    availableSlots: 12,
  },
  {
    id: 'p2',
    name: 'Улсын их дэлгүүрийн зогсоол',
    address: 'Энхтайваны өргөн чөлөө',
    lat: 47.916,
    lng: 106.903,
    priceMNT: 1500,
    available: true,
    distanceKm: 1.2,
    totalSlots: 30,
    availableSlots: 5,
  },
  {
    id: 'p3',
    name: 'Шангри-Ла төвийн зогсоол',
    address: 'Олимпийн гудамж',
    lat: 47.913,
    lng: 106.920,
    priceMNT: 3000,
    available: false,
    distanceKm: 0.8,
    totalSlots: 100,
    availableSlots: 0,
  },
  {
    id: 'p4',
    name: 'Төв номын сангийн зогсоол',
    address: 'Чингисийн өргөн чөлөө',
    lat: 47.914,
    lng: 106.915,
    priceMNT: 1000,
    available: true,
    distanceKm: 0.9,
    totalSlots: 20,
    availableSlots: 8,
  },
  {
    id: 'p5',
    name: '13-р хорооллын зогсоол',
    address: 'Энхтайваны өргөн чөлөө 13',
    lat: 47.919,
    lng: 106.945,
    priceMNT: 1000,
    available: true,
    distanceKm: 2.5,
    totalSlots: 40,
    availableSlots: 25,
  },
];
